insert into project2.external_attractions (name, ratings, imageurl)
values
	('Formula Rossa', 10, 'https://rcdb.com/4485.htm#'),
	('Kingda Ka', 10, 'https://rcdb.com/2832.htm#'),
	('Top Thrill', 10,'https://rcdb.com/1896.htm#'),
	('Do-Dodonpa', 10,'https://rcdb.com/1423.htm#'),
	('Red Force',	10, 'https://rcdb.com/10698.htm'),
	('Superman: Escape from Krypton', 10, 'https://rcdb.com/140.htm'),
	('Tower of Terror II',	10, 'https://rcdb.com/1127.htm'),
	('Ring Racer',		10,'https://rcdb.com/4161.htm'),
	('Steel Dragon 2000', 10, 'https://rcdb.com/1173.htm'),
	('Fury 325', 10, 'https://rcdb.com/12273.htm'),
	('Millennium Force', 9,'https://rcdb.com/594.htm'),
	('Leviathan', 9, 'https://rcdb.com/10108.htm'),
	('Orion', 9, 'https://rcdb.com/11437.htm'),
	('Intimidator 305',	9 , 'https://rcdb.com/4520.htm'),
	('Hyperion', 9, 'https://rcdb.com/14462.htm'),
	('Phantom Revenge',	9, 'https://rcdb.com/123.htm'),
	('Goliath',	9, 'https://rcdb.com/615.htm'),
	('Titan',	9, 'https://rcdb.com/742.htm'),
	('Coaster Through the Clouds', 8, 'https://rcdb.com/9863.htm') ,
	('Furius Baco',	8, 'https://rcdb.com/3430.htm'),
	('Launch Coaster', 8, 'https://rcdb.com/12256.htm'), 
    ('Shambhala',	8, 'https://rcdb.com/10239.htm'),
	('Extreme Rusher', 8, 'https://rcdb.com/9140.htm' ),
	('Bullet Coaster', 8, 'https://rcdb.com/9442.htm' ),
	('OCT Thrust SSC1000',8 ,'https://rcdb.com/10077.htm'),
	('Xcelerator',8 ,'https://rcdb.com/1574.htm'),
	('Fujiyama',8 ,'https://rcdb.com/1190.htm'),
	('Thunder Dolphin',8 ,'https://rcdb.com/1845.htm'),
	('Yukon Striker',8 ,'https://rcdb.com/16021.htm'),
	('Zaturn',8 ,'https://rcdb.com/3454.htm'),
	('Desperado',8 ,'https://rcdb.com/103.htm'),
	('HyperSonic XLC',8 ,'https://rcdb.com/729.htm'),
	('Nitro',8 ,'https://rcdb.com/1106.htm'),
	('Stealth',8 ,'https://rcdb.com/3081.htm'),
	('Diamondback',8 ,'https://rcdb.com/4253.htm'),
	('Silver Star',7 ,'https://rcdb.com/1414.htm'),
	('Schwur des Kärnan',7 ,'https://rcdb.com/11615.htm'),
	('Son Of Beast',7 ,'https://rcdb.com/584.htm'),
	('Eejanaika',7 ,'https://rcdb.com/3254.htm'),
	('Dinoconda',7 ,'https://rcdb.com/9040.htm'),
	('Maxx Force',7 ,'https://rcdb.com/16586.htm'),
	('Soaring with Dragon',7 ,'https://rcdb.com/13420.htm'),
	('Superman the Ride',7 ,'https://rcdb.com/628.htm'),
	('Behemoth',7 ,'https://rcdb.com/4005.htm'),
	('X2',7 ,'https://rcdb.com/750.htm'),
	('Candymonium',7 ,'https://rcdb.com/16682.htm'),
	('Iron Gwazi',7 ,'https://rcdb.com/16985.htm'),
	('Zadra',7 ,'https://rcdb.com/16184.htm'),
	('Steel Force',7 ,'https://rcdb.com/276.htm'),
	('Mamba',7 ,'https://rcdb.com/469.htm'),
	('Storm Runner',7 ,'https://rcdb.com/2498.htm'),
	('Intimidator',7 ,'https://rcdb.com/8588.htm'),
	('Skyrush',7 ,'https://rcdb.com/10089.htm'),
	('Valravn',7 ,'https://rcdb.com/13383.htm'),
	('Steel Curtain',7 ,'https://rcdb.com/16479.htm'),
	('Expedition GeForce',7 ,'https://rcdb.com/977.htm'),
	('Superman el Último Escape',7 ,'https://rcdb.com/2829.htm'),
	('Flying Aces',7 ,'https://rcdb.com/12772.htm'),
	('Wild Thing',7 ,'https://rcdb.com/137.htm'),
	('Big One',7 ,'https://rcdb.com/775.htm'),
	('Steel Vengeance',7 ,'https://rcdb.com/15411.htm'),
	('Falcon',7 ,'https://rcdb.com/12413.htm'),
	('Apollos Chariot',7,'https://rcdb.com/531.htm'),
	('Raging Bull',7,'https://rcdb.com/535.htm'),
	('Ride of Steel',7,'https://rcdb.com/541.htm'),
	('Superman - Ride Of Steel',7,'https://rcdb.com/699.htm'),
	('Mako',7,'https://rcdb.com/12758.htm'),
	('Lightning Rod',7 ,'https://rcdb.com/13369.htm'),
	('Pantheon',7 ,'https://rcdb.com/16812.htm'),
	('Taron',7 ,'https://rcdb.com/12723.htm'),
	('Magnum XL-200',7 ,'https://rcdb.com/11.htm'),
	('Wicked Twister',7 ,'https://rcdb.com/1571.htm'),
	('Goliath',7 ,'https://rcdb.com/9972.htm'),
	('Titan MAX',7 ,'https://rcdb.com/1194.htm'),
	('Flash',7 ,'https://rcdb.com/6764.htm'),
	('Wildfire',7 ,'https://rcdb.com/12032.htm'),
	('DC Rivals HyperCoaster',7 ,'https://rcdb.com/13637.htm'),
	('Hyper Coaster',7 ,'https://rcdb.com/14440.htm'),
	('Wrath Of Zeus',7 ,'https://rcdb.com/14492.htm'),
	('Griffon',7 ,'https://rcdb.com/3631.htm'),
	('Viper',7 ,'https://rcdb.com/25.htm'),
	('Mr. Freeze Reverse Blast',7 ,'https://rcdb.com/281.htm'),
	('Mr. Freeze Reverse Blast',7 ,'https://rcdb.com/427.htm'),
	('Volcano, The Blast Coaster',7 ,'https://rcdb.com/474.htm'),
	('Speed - The Ride',7 ,'https://rcdb.com/593.htm'),
	('Superman Krypton Coaster',7 ,'https://rcdb.com/605.htm'),
	('Steel Venom',7 ,'https://rcdb.com/631.htm'),
	('Vertical Velocity',7 ,'https://rcdb.com/747.htm'),
	('SheiKra',7 ,'https://rcdb.com/2662.htm'),
	('El Toro',7 ,'https://rcdb.com/3183.htm'),
	('Goliath',7 ,'https://rcdb.com/3290.htm'),
	('Maverick',7 ,'https://rcdb.com/3570.htm'),
	('Possessed',7 ,'https://rcdb.com/4039.htm'),
	('Full Throttle',7 ,'https://rcdb.com/10948.htm'),
	('Cannibal',7 ,'https://rcdb.com/11579.htm'),
	('Iron Rattler',7 ,'https://rcdb.com/11663.htm'),
	('Dive Coaster',6 ,'https://rcdb.com/3930.htm'),
	('Colossos - Kampf der Giganten',6 ,'https://rcdb.com/988.htm'),
	('Bandit',6 ,'https://rcdb.com/1218.htm'),
	('iSpeed',6 ,'https://rcdb.com/4147.htm'),
	('Diving Machine G5',6 ,'https://rcdb.com/1417.htm'),
	('Goliath',6 ,'https://rcdb.com/3385.htm'),
	('Red Fire',6 ,'https://rcdb.com/7395.htm'),
	('Nefeskesen',6 ,'https://rcdb.com/10831.htm'),
	('Great American Scream Machine',6 ,'https://rcdb.com/34.htm'),
	('Oblivion',6 ,'https://rcdb.com/777.htm'),
	('Steel Venom',6 ,'https://rcdb.com/1920.htm'),
	('Banshee',6 ,'https://rcdb.com/6640.htm'),
	('Outlaw Run',6 ,'https://rcdb.com/10582.htm'),
	('Big Air',6 ,'https://rcdb.com/8656.htm'),
	('Parrot Coaster',6 ,'https://rcdb.com/9114.htm'),
	('Big Apple Coaster',6 ,'https://rcdb.com/139.htm'),
	('Alpengeist',6 ,'https://rcdb.com/277.htm'),
	('Incredible Hulk',6 ,'https://rcdb.com/557.htm'),
	('Voyage',6 ,'https://rcdb.com/3231.htm'),
	('GateKeeper',6 ,'https://rcdb.com/10891.htm'),
	('Hakugei',6 ,'https://rcdb.com/15515.htm'),
	('Boss',6 ,'https://rcdb.com/616.htm'),
	('Fury',6 ,'https://rcdb.com/16110.htm'),
	('American Eagle',6 ,'https://rcdb.com/9.htm'),
	('Wildfire',6 ,'https://rcdb.com/720.htm'),
	('Goliath',6 ,'https://rcdb.com/1565.htm'),
	('Taiga',6 ,'https://rcdb.com/16138.htm'),
	('Déjà Vu',6 ,'https://rcdb.com/746.htm'),
	('Déjà Vu',6 ,'https://rcdb.com/748.htm'),
	('Déjà Vu',6 ,'https://rcdb.com/1040.htm'),
	('Stunt Fall',6 ,'https://rcdb.com/1369.htm'),
	('Aftershock',6 ,'https://rcdb.com/4155.htm'),
	('Sky Mountain',6 ,'https://rcdb.com/8976.htm'),
	('Giant Inverted Boomerang',6 ,'https://rcdb.com/9564.htm'),
	('Goliath',6 ,'https://rcdb.com/10138.htm'),
	('Quantum Leap',6,'https://rcdb.com/10837.htm'),
	('Sky Wheel',6 ,'https://rcdb.com/2773.htm'),
	('X Coaster',6 ,'https://rcdb.com/3312.htm'),
	('Magic Ring Vertical Coaster',6 ,'https://rcdb.com/6489.htm'),
	('Terror Twister',6 ,'https://rcdb.com/7027.htm'),
	('Clouds of Fairyland',6 ,'https://rcdb.com/8982.htm'),
	('Hidden Anaconda',6 ,'https://rcdb.com/9095.htm'),
	('Great Bear',5 ,'https://rcdb.com/468.htm'),
	('Talon',5 ,'https://rcdb.com/735.htm'),
	('Fahrenheit',5 ,'https://rcdb.com/4049.htm'),
	('Medusa Steel Coaster',5 ,'https://rcdb.com/11664.htm'),
	('Jersey Devil Coaster',5 ,'https://rcdb.com/17658.htm'),
	('Aconcagua',5 ,'https://rcdb.com/1504.htm'),
	('Thundercoaster',5 ,'https://rcdb.com/1042.htm'),
	('Magnus Colossus',5 ,'https://rcdb.com/1081.htm'),
	('Untamed',5 ,'https://rcdb.com/16047.htm'),
	('Raptor',5 ,'https://rcdb.com/1.htm'),
	('Tidal Wave',5 ,'https://rcdb.com/38.htm'),
	('Viper',5 ,'https://rcdb.com/39.htm'),
	('Great American Scream Machine',5 ,'https://rcdb.com/41.htm'),
	('Greased Lightnin',5 ,'https://rcdb.com/75.htm'),
	('Shivering Timbers',5 ,'https://rcdb.com/478.htm'),
	('Rock n Roller Coaster',5 ,'https://rcdb.com/560.htm'),
	('Mega Zeph',5 ,'https://rcdb.com/589.htm'),
	('White Lightnin',5 ,'https://rcdb.com/667.htm'),
	('Golden Loop',5 ,'https://rcdb.com/1168.htm'),
	('Shuttle Loop',5 ,'https://rcdb.com/1177.htm'),
	('Shuttle Loop',5 ,'https://rcdb.com/1205.htm'),
	('Rock n Roller Coaster',5 ,'https://rcdb.com/1444.htm'),
	('Greezed Lightnin',5 ,'https://rcdb.com/2216.htm'),
	('Greased Lightnin',5,'https://rcdb.com/2379.htm'),
	('Mind Eraser',4 ,'https://rcdb.com/430.htm'),
	('Riddler Revenge',4 ,'https://rcdb.com/429.htm'),
	('Mind Eraser',4 ,'https://rcdb.com/422.htm'),
	('Thunderhawk',4 ,'https://rcdb.com/489.htm'),
	('Serial Thriller',4 ,'https://rcdb.com/551.htm'),
	('Twisted Typhoon',4 ,'https://rcdb.com/561.htm'),
	('Batman The Ride',4 ,'https://rcdb.com/639.htm'),
	('Condor',4 ,'https://rcdb.com/770.htm'),
	('Robin Hood',4 ,'https://rcdb.com/771.htm'),
	('Traumatizer',4 ,'https://rcdb.com/805.htm'),
	('Vampire',4 ,'https://rcdb.com/922.htm'),
	('Blue Tornado',4 ,'https://rcdb.com/961.htm'),
	('Jaguar',4 ,'https://rcdb.com/964.htm'),
	('Bandit',4 ,'https://rcdb.com/967.htm'),
	('Lucky Luke - The Ride: Die Daltons brechen aus',4 ,'https://rcdb.com/969.htm'),
	('Euro Mir',4 ,'https://rcdb.com/972.htm'),
	('Limit',4 ,'https://rcdb.com/987.htm'),
	('Loup-Garou',4 ,'https://rcdb.com/1029.htm'),
	('Lisebergbanan',4 ,'https://rcdb.com/1061.htm'),
	('Tornado',4 ,'https://rcdb.com/1101.htm'),
	('Arkham Asylum - Shock Therapy',4 ,'https://rcdb.com/1122.htm'),
	('Monte Makaya',4 ,'https://rcdb.com/1145.htm'),
	('Cobra',4 ,'https://rcdb.com/1165.htm'),
	('Double Loop',4 ,'https://rcdb.com/1201.htm'),
	('Nio',4 ,'https://rcdb.com/1211.htm'),
	('Atomic',4 ,'https://rcdb.com/1216.htm'),
	('Blackout',4 ,'https://rcdb.com/1224.htm'),
	('Aska',4 ,'https://rcdb.com/1244.htm'),
	('Mayan Adventure',4 ,'https://rcdb.com/1231.htm'),
	('Sky Loop',4 ,'https://rcdb.com/1250.htm'),
	('Hurricane',4 ,'https://rcdb.com/1260.htm'),
	('Camel Coaster',4 ,'https://rcdb.com/1264.htm'),
	('F2 Fright Flight',4 ,'https://rcdb.com/1267.htm'),
	('Atomic Coaster',4 ,'https://rcdb.com/1296.htm'),
	('Desafío',4 ,'https://rcdb.com/1322.htm'),
	('Atomic Coaster',4 ,'https://rcdb.com/1341.htm'),
	('Roller Coaster',4 ,'https://rcdb.com/1348.htm'),
	('Batman: Arkham Asylum',4 ,'https://rcdb.com/1365.htm'),
	('Loop Screw',4 ,'https://rcdb.com/1429.htm'),
	('Kumba',4 ,'https://rcdb.com/1559.htm'),
	('Titánide',4 ,'https://rcdb.com/1799.htm'),
	('Giant Coaster',4 ,'https://rcdb.com/2073.htm'),
	('Silber Mine',4 ,'https://rcdb.com/2204.htm'),
	('Typhoon',4 ,'https://rcdb.com/2229.htm'),
	('Gauntlet',4 ,'https://rcdb.com/2421.htm'),
	('Dangai',4 ,'https://rcdb.com/2691.htm'),
	('Shenzhou Coaster',4 ,'https://rcdb.com/2906.htm'),
	('Atlantica SuperSplash',4 ,'https://rcdb.com/2928.htm'),
	('Black Mamba',4 ,'https://rcdb.com/3117.htm'),
	('Motorbike Launch Coaster',4 ,'https://rcdb.com/3418.htm'),
	('Flight of the Phoenix',4 ,'https://rcdb.com/3448.htm'),
	('Feng Shen Coaster',4 ,'https://rcdb.com/3503.htm'),
	('Muntanya Russa',4 ,'https://rcdb.com/3596.htm'),
	('Infusion',4 ,'https://rcdb.com/3672.htm')
;